### ISSUE TITLE
a C++ wrapper for FFmpeg may help

### ISSUE THREAD

**Issue by insilications** [theophanemayaud/video-simili-duplicate-cleaner#1]
Hey, I see that you are implementing static linking with ffmpeg. This library is complete and may help with the process: https://github.com/h4tr3d/avcpp. Just an idea.

**Comment by theophanemayaud** [comment]
Thanks for the tip !!! 
I had a look already while trying to figure it out ! But I was having linking problems which I wasn’t ready to handle because I didn’t know enough. I therefore learned to work through the problems. I am using qt qmake not cmake, and didn’t directly find the example I needed.  

I finally figured it out and started migrating some ffmpeg calls via the old executable to the static library. I don’t see why there should be wrappers though... the C calls seem pretty simple to me ! Maybe I’ll stumble upon problems later on, but it seems using the C functions is easy. Setting the linking wasn’t. Do you know why it’d be useful ?

**Comment by theophanemayaud** [comment]
So again, thanks for the tip ! I'll keep working on it :)
