### ISSUE TITLE
Some UI improvements

### ISSUE THREAD

**Issue by newadventure079** [theophanemayaud/video-simili-duplicate-cleaner#105]
1.  It would be nice if the UI slider for the comparison threshold value showed the value on the UI, instead of having to hover over the slider and wait for the tooltip to appear to tell us the value.  Please add a new text element that would dynamically show the value on the UI, similar to the red text on my mockup
![Screenshot 2023-03-07 at 6 13 36 PM](https://user-images.githubusercontent.com/84156407/223593841-c0aace97-8db6-4ed0-b822-a0125912038b.jpg)

2.  Several text elements either appear to be left-aligned, right-aligned, or indented a few spaces, but there's no consistency at all.   
For example, the Path value is right-aligned and is a mile away from the text element `Path:`
`File size:`'s value has nice spacing but `Duration`, `codec` and `file created` values are way apart from their text element
This makes the values hard to read and easily decifer.
![Screenshot 2023-03-07 at 6 09 21 PM](https://user-images.githubusercontent.com/84156407/223593849-d9a16681-503f-4c86-abed-835b06bc02e8.jpg)

**Comment by theophanemayaud** [comment]
First : the path is right aligned as I find it most useful to have the rightmost part of the path in case it is longer than the available space. So this is my way of truncating the left part of the path instead of the left. I haven't found an easy way to do it otherwise.
For the other elements : I fixed the alignment as you suggested ! Thanks a lot :) 
I also added the threshold slider text.

Fixed with d0282f31ce37e818527daa04a93f8684f8f396dc, which also fixed a minor coloring glitch for audio and video codec comparison.
