### ISSUE TITLE
File link hardly visible in dark mode

### ISSUE THREAD

**Issue by theophanemayaud** [theophanemayaud/video-simili-duplicate-cleaner#94]
As per user review in App Store, the blue file link in comparison window is hardly visible in dark mode. 
Probably a problem of non Qt-handled color. Solution might be to use a qt dark mode friendly color palette if that exists ?

**Comment by theophanemayaud** [comment]
I noticed using QT Creator that I have this exact problem. QT Creator text of hyperlinks are basically invisible in dark mode. So it's an upstream problem. Should probably create QT bug report...

**Comment by Daveja-Vu** [comment]
Just purchased this, and it's outstanding, but wanted to +1 this issue because it's a major usability issue, for me anyway. The bright blue on black is extremely difficult to read and some of the workflows I'm using are filename-dependent. Completely understand it's a QT thing, but maybe a different background color for just the link section? Or display the filename not as a link and have a button next to it or something?

**Comment by theophanemayaud** [comment]
Hey @Daveja-Vu sorry for being so late to address the issue. But i just published v1.11.0 that should fix this ! I modified the color to be visible in both dark and light mode. Please let me know if you still have suggestions ☺️

**Comment by Daveja-Vu** [comment]
Works perfectly - thank you!
